
**Importing the pandas and initializing the array**



>



In [2]:
#Importing the pandas libraries
import numpy as np

# Initialising the aray---
arr = np.array([1,2,3])
arr # You get the array without printing
arr.ndim #gives the dimention of the array
arr.shape #gives the shape of the array
range = np.arange(1,10,2)#gives start,stop and step value
print(range)
arr = np.linspace(0,1,5)# Here the last value represents the number of values evenly spaces between the start and stop value
print(arr)
arr = np.logspace(1,2,3)# same but takes the log as value.
print(arr)              #eg-log(1) = 10
arr = np.zeros(5)      # gives array with zeroes with number in the bracket
print(arr)
arr = np.ones(5)       # gives array with 1 with number in the bracket
print(arr)
arr = np.full(10,2)  # here 10 gives the number of repetition and 2 the value to be repited
print(arr)
arr = np.empty([])    #Creates a empty array wothout setting any values
print(arr)          # 1.In reality the array is uninitialized 2. To initialize give the shape to the array by adding []
arr = np.random.rand(2,3)  # Creates the randome floates between 0 to 1
print(arr)
arr = np.random.randint(1,10 ,size = (12,3))# random integers are printed
print(arr)  # 12 gives the rows and 3 columns by convention as
arr = np.random.randn(4)# prints the random variable with mean = 0 and S.D. = 1
arr





[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[ 10.         31.6227766 100.       ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[2 2 2 2 2 2 2 2 2 2]
1e-323
[[0.80751651 0.01592023 0.43845627]
 [0.93622716 0.42361755 0.91065728]]
[[1 9 3]
 [8 5 7]
 [5 4 5]
 [6 8 6]
 [9 8 2]
 [7 2 6]
 [4 4 4]
 [4 6 7]
 [2 1 7]
 [5 5 5]
 [6 7 5]
 [8 8 6]]


array([ 1.03078427,  1.08467382,  0.15633817, -0.91824255])

**Numpy data types and typecasting**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
# prints [1,2,3,4,5] where the datatype is an integer
arr = np.array([1,2.3,3,4,5])
arr.dtype   # One float value changes the aray to float
arr = np.array(['string',2,3,4,5])
arr.dtype    # One string converts the array into a string (U21)
# To manually convert the datatype
arr = np.array([1,2.4,3,4,5],dtype = np.int64) # converts the float to a integer and the decimal value is lost
arr
arr.dtype
# To type cast manually we have to take into account that only to those datatype we can convert the array to which
# the array can convert  its all elements
arr1 = np.array(["String",2,3,4,5])
# arr2 = arr1.astype(np.int64) - takes the value of another array, typecasts and stores into another array.
# arr2
# gives type error because the string cannot be converted into integer



[1 2 3 4 5]


**Creating arrays mannually**


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim
arr.size
arr.shape
arr.itemsize# gives the total number of elements in the array



8

**Array reshaping**

In [ ]:
#Using the Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3) # Converts the single row into 2 row and 3 coloumn
print(reshaped)

#Using ravel
#ravel converts any array to 1d
arr = np.array([[1,2,3],[4,5,6]])
ravelled = arr.ravel()
print(ravelled)

ravelled[0] = 100
print(ravelled)
print(arr)

#Using flatten
flat = arr.flatten()
print(flat)
flat[0] = 100
print(flat)
print(arr)
# *The key takeaway is that the changes applied to ravel affect original array whereas in flatten not as it returns the copy*





[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


**Arithmetic operations**

In [ ]:
#Some simple arithematic operations
a  = np.array([1,2,3,4,5])
b= np.array([2,4,5,67,6])# The dimension should be same of both arrays as the operation applied is from element to element
print(a+b)
print(a-b)
print(a/b)
print(a*b)

#Universal functions-ufuncs
arr = np.array([1,4,9,16,25])
print(np.sqrt(arr))#prints the square root of the array elements

#Sine functions-np.sin
angles = np.array([0,np.pi,np.pi/2])# Here the valules are the angles of trignometry functions
print(np.sin(angles))
# Same for the other trignometry functions
print(np.cos(angles))
print(np.tan(angles))






[ 3  6  8 71 11]
[ -1  -2  -2 -63  -1]
[0.5        0.5        0.6        0.05970149 0.83333333]
[  2   8  15 268  30]
[1. 2. 3. 4. 5.]
[0.0000000e+00 1.2246468e-16 1.0000000e+00]


**Indexing and slicing**

In [ ]:
a = [1,2,3,4,5]
b = (a[-1:-4:-1])
b = (a[::2])# takes start and last value and the step value to trim
print(a[1])# Indexing from front
print(a[-3])# indexing from behind

a
b


2
3


[1, 3, 5]

**Iterating**

In [10]:
#nditer() lets us iterate over any array
arr = np.array([[1,2],[3,4]])
for x in np.nditer(arr):
      print(x,end=" ")#prints in the same line while( " " ) gives the space between each elements
#ndenumerate() gives both index and value
arr = np.array([1,2,3,4,5])
for x in np.ndenumerate(arr):
      print(x)


1 2 3 4 ((0,), np.int64(1)) ((1,), np.int64(2)) ((2,), np.int64(3)) ((3,), np.int64(4)) ((4,), np.int64(5)) 

**Views vs Copies**

In [22]:
#view
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view[0] = 200
view
arr

#copy
arr = np.array([1,2,3,4,5])
copy = arr[1:3].copy()
copy[0] = 200
copy
arr
#Original array is not changed in copy , while it is changed in the view

array([1, 2, 3, 4, 5])

Swapaxes


In [20]:
#Swapaxes- This swaps 2 specific axes in a matrix
arr  = np.array([[[1,2,3],[3,4,6]]])
arr.shape
swapped = np.swapaxes(arr,0,1)# Swapes the array axes
swapped.shape




(2, 1, 3)

 ***Concatenation***

In [30]:
#Concatenate
# Used for combining two arrays sidewise
a = np.array([1,2])
b = np.array([3,4])
combine =  np.concatenate((a,b))
combine

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6], [7,8]])
print(np.hstack((arr1,arr2)))# stacks array sideways
print(np.vstack((arr1,arr2)))# stacks array one upon another

# Other methods
print(np.stack((arr1,arr2),axis = 0))
print(np.stack((arr1,arr2),axis = 1))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


***Splitting of the array***

In [32]:
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr1,2))# splits the array in 2 parts
# NOTE - The arrays are split evenly by row hence to split in 3 parts is invalid




[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


**Repeation of the array**

In [36]:
#Repeat
arr = np.array([1,2,3])
print(np.repeat(arr,3))
# Here each element is repeated thrice

#Tile
print(np.tile(arr,2))
# Here the row is repeated twice



[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3]


**Aggregate function and Cumalative operations**


In [40]:
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))# prints the standard deviation of the elements in the array

#Cumalative operation
arr = np.array([1,2,3])
print(np.cumsum(arr))
print(np.cumprod(arr))

# Gives cumalitive sum [ 1st element ,1st element+2nd element,1st element+2nd element+3rd element]
# Gives cumalitive product [  1stelement ,1st element*2nd element,1st element*2nd element*3rd element]


6
2.0
2.0
1
3
0.816496580927726
[1 3 6]
[1 2 6]


**Where and agwhere**

In [43]:
#Where
arr = np.array([1,2,3])
result = np.where(arr<2,'low','high')
result
#prints low when the condition is met and high when it's not.

#Argwhere
arr = np.array([10,25,30,50])
print(np.argwhere(arr>20))
#gives the indexes where the condition is met



[[1]
 [2]
 [3]]


**Advanve condition operations**

In [46]:
#logical_and
arr = np.array([100,2,3,4,5,6])
mask = np.logical_and(arr>3,arr<6)# sets the boundary
print(mask)#prints the true and false
arr[mask]# prints the elements which meet the criteria

#logical_or
arr = np.array([100,2,3,4,5,6])
mask = np.logical_orr(arr>3,arr<6)# sets the boundary
print(mask)#prints the true and false
arr[mask]# prints the elements which does not meet the criteria of logical_and(for understanding)




[False False False  True  True False]


array([4, 5])

**Broadcasting and vectorization**

In [50]:
#BROADCASTING
# To make the smaller array stretch to match the bigger array
# condition- One array has to be of 1D
image = np.array([[200,500],[250,100]])
brightness = image + 50
brightness
# 50 is added to each element

#VECTORIZATION
#np.vectorize - converts a regular function to be applied on an array
def square(x):
   return x*x
arr = np.array([1,2,3,4,5,6])
vfunc = np.vectorize(square)
vfunc(arr)




array([ 1,  4,  9, 16, 25, 36])

**Handling missing values**

In [67]:
#Detecting
arr = np.array([1,2,np.nan,4,5])
print(np.isnan(arr))
det1 = np.where(arr == 2)#by value position
det1 = np.where(arr>25)#by condition
det1

#Deleting
arr = np.array([10,20,30,40,50])
del1 = np.delete(arr,2)#deletes element at index 2
del1
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
del2 = np.delete(mat,1,axis = 0)#deleting row wise
del3 = np.delete(mat,1,axis = 1)# deleting column wise
print(del2)
print(del3)

#Update
arr[2] = 100
mat[1,2] = 50
arr[arr>25]  = -1
arr
#Inserting
arr = np.insert(arr,2,99)
np.insert(mat,1,[11,11,11],axis = 0)
mat  = np.insert(mat,1,[11,11,11],axis = 1)
print(arr)
print(mat)

[False False  True False False]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
[10 20 99 -1 -1 -1]
[[ 1 11  2  3]
 [ 4 11  5 50]
 [ 7 11  8  9]]
